[workspace]
members = [
    "crates/domain",
    "crates/application",
    "crates/infrastructure",
    "crates/persistence",
    "crates/transport",
    "crates/runtime",
    "crates/runtime-tokio",
    "crates/event-adapter",
    "crates/persistent-entity",
    "crates/ego-scheduler",
    "crates/service-sdk",
    "crates/service-sdk-macros",
    "crates/security-sdk",
    "crates/security-jwt",
    "crates/config-sdk",
]
resolver = "2"

[workspace.dependencies]
mockall = "0.14.0"
async-trait = "0.1"
