[workspace]
members = [
    "crates/domain",
    "crates/application",
    "crates/infrastructure",
    "crates/persistence",
    "crates/transport",
    "core/runtime-slice",
    "crates/runtime",
    "crates/runtime-tokio",
    "crates/event-adapter",
    "crates/persistent-entity",
    "crates/ego-scheduler",
]
resolver = "2"

[workspace.dependencies]
mockall = "0.14.0"
async-trait = "0.1"
