[package]
name = "ego-runtime"
version = "0.1.0"
edition = "2021"

[dependencies]
ego-domain = { path = "../domain" }
uuid = { version = "1", features = ["v4"] }
tokio = { version = "1", features = ["rt-multi-thread", "sync", "macros"] }
async-trait = "0.1"
thiserror = "1"

[dev-dependencies]
tokio = { version = "1", features = ["rt-multi-thread", "sync", "macros", "test-util", "time"] }
serde_json = "1"
chrono = { version = "0.4", features = ["serde"] }
