[package]
name = "ego-persistence-api"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1", features = ["derive"] }
thiserror = "1"
chrono = { version = "0.4", features = ["serde"] }
async-trait = { workspace = true }

[dev-dependencies]
tokio = { version = "1", features = ["full"] }
