use std::collections::HashMap;

// CORE-PERSIST-A S2 (AD-3): the `id_type!` generator relocated to
// `ego-persistence-api` and is `#[macro_export]`ed. Re-invoked here for
// this crate's remaining identity types instead of duplicating the
// definition — one generator, not two.
pub(crate) use ego_persistence_api::id_type;

// CORE-PERSIST-A S2 (AD-3): `TenantId`/`TenantIdError` are now generated by
// the relocated macro; re-exported here so `ego_domain::context::TenantId`
// (and, via lib.rs, `ego_domain::TenantId`) keeps resolving to the
// identical type.
pub use ego_persistence_api::context::{TenantId, TenantIdError};

// ---------------------------------------------------------------------------
// Identity types
// ---------------------------------------------------------------------------

id_type!(
    AggregateId,
    AggregateIdError,
    "aggregate_id must not be empty"
);
id_type!(EntityId, EntityIdError, "entity_id must not be empty");
id_type!(
    CorrelationId,
    CorrelationIdError,
    "correlation_id must not be empty"
);
id_type!(
    CausationId,
    CausationIdError,
    "causation_id must not be empty"
);
id_type!(RequestId, RequestIdError, "request_id must not be empty");

/// Arbitrary key-value metadata attached to an execution context.
pub type Metadata = HashMap<String, String>;

#[cfg(test)]
mod tests {
    use super::*;

    // -----------------------------------------------------------------------
    // Identity type tests
    // -----------------------------------------------------------------------

    #[test]
    fn test_aggregate_id_valid() {
        let id = AggregateId::new("agg-123").unwrap();
        assert_eq!(id.as_str(), "agg-123");
    }

    #[test]
    fn test_aggregate_id_empty_rejected() {
        let err = AggregateId::new("").unwrap_err();
        assert_eq!(err, AggregateIdError);
    }

    #[test]
    fn test_aggregate_id_whitespace_rejected() {
        let err = AggregateId::new("   ").unwrap_err();
        assert_eq!(err, AggregateIdError);
    }

    #[test]
    fn test_aggregate_id_deserialize_validates() {
        let id: AggregateId = serde_json::from_str("\"agg-123\"").unwrap();
        assert_eq!(id.as_str(), "agg-123");
        assert!(serde_json::from_str::<AggregateId>("\"\"").is_err());
        assert!(serde_json::from_str::<AggregateId>("\"   \"").is_err());
    }

    #[test]
    fn test_entity_id_valid() {
        let id = EntityId::new("ent-456").unwrap();
        assert_eq!(id.as_str(), "ent-456");
    }

    #[test]
    fn test_entity_id_empty_rejected() {
        let err = EntityId::new("").unwrap_err();
        assert_eq!(err, EntityIdError);
    }

    #[test]
    fn test_entity_id_deserialize_validates() {
        let id: EntityId = serde_json::from_str("\"ent-456\"").unwrap();
        assert_eq!(id.as_str(), "ent-456");
        assert!(serde_json::from_str::<EntityId>("\"\"").is_err());
        assert!(serde_json::from_str::<EntityId>("\"   \"").is_err());
    }

    // `TenantId` tests moved to `ego-persistence-api`'s `context.rs` with the
    // relocated `id_type!` macro invocation that generates it (CORE-PERSIST-A
    // S2, AD-3, D-6).

    #[test]
    fn test_correlation_id_valid() {
        let id = CorrelationId::new("corr-789").unwrap();
        assert_eq!(id.as_str(), "corr-789");
    }

    #[test]
    fn test_correlation_id_empty_rejected() {
        let err = CorrelationId::new("").unwrap_err();
        assert_eq!(err, CorrelationIdError);
    }

    #[test]
    fn test_correlation_id_deserialize_validates() {
        let id: CorrelationId = serde_json::from_str("\"corr-789\"").unwrap();
        assert_eq!(id.as_str(), "corr-789");
        assert!(serde_json::from_str::<CorrelationId>("\"\"").is_err());
        assert!(serde_json::from_str::<CorrelationId>("\"   \"").is_err());
    }

    #[test]
    fn test_causation_id_valid() {
        let id = CausationId::new("cause-001").unwrap();
        assert_eq!(id.as_str(), "cause-001");
    }

    #[test]
    fn test_causation_id_empty_rejected() {
        let err = CausationId::new("").unwrap_err();
        assert_eq!(err, CausationIdError);
    }

    #[test]
    fn test_causation_id_deserialize_validates() {
        let id: CausationId = serde_json::from_str("\"cause-001\"").unwrap();
        assert_eq!(id.as_str(), "cause-001");
        assert!(serde_json::from_str::<CausationId>("\"\"").is_err());
        assert!(serde_json::from_str::<CausationId>("\"   \"").is_err());
    }

    #[test]
    fn test_request_id_valid() {
        let id = RequestId::new("req-999").unwrap();
        assert_eq!(id.as_str(), "req-999");
    }

    #[test]
    fn test_request_id_empty_rejected() {
        let err = RequestId::new("").unwrap_err();
        assert_eq!(err, RequestIdError);
    }

    #[test]
    fn test_request_id_deserialize_validates() {
        let id: RequestId = serde_json::from_str("\"req-999\"").unwrap();
        assert_eq!(id.as_str(), "req-999");
        assert!(serde_json::from_str::<RequestId>("\"\"").is_err());
        assert!(serde_json::from_str::<RequestId>("\"   \"").is_err());
    }

    #[test]
    fn test_id_equality() {
        let a = AggregateId::new("foo").unwrap();
        let b = AggregateId::new("foo").unwrap();
        let c = AggregateId::new("bar").unwrap();
        assert_eq!(a, b);
        assert_ne!(a, c);
    }

    #[test]
    fn test_id_clone() {
        let a = AggregateId::new("clone-me").unwrap();
        let b = a.clone();
        assert_eq!(a, b);
    }

    #[test]
    fn test_id_debug() {
        let id = AggregateId::new("debug-test").unwrap();
        let debug = format!("{:?}", id);
        assert!(debug.contains("AggregateId"));
        assert!(debug.contains("debug-test"));
    }

    #[test]
    fn test_id_hash() {
        use std::collections::HashSet;
        let mut set = HashSet::new();
        set.insert(AggregateId::new("hash-test").unwrap());
        set.insert(AggregateId::new("hash-test").unwrap());
        assert_eq!(set.len(), 1);
    }
}
