//! Golden (snapshot) tests for `#[service]` macro expansion.
//!
//! These tests capture the observable output of generated code and compare
//! against approved snapshots. A snapshot change means the macro output
//! changed — review carefully.
//!
//! Run to update: `cargo test -p ego-service-sdk golden_`
//! Approve snapshots: `cargo insta review` or `INSTA_UPDATE=always cargo test`
//!
//! NOTE: TypeId values are non-deterministic across compilations. These tests
//! use `insta::with_settings!` + `filters` to normalise them to `TypeId(<opaque>)`.

use ego_service_sdk::contract::ServiceContract;
use ego_service_sdk::di::{AdapterRef, Injectable, ProjectionRef};
use ego_service_sdk::error::category::ErrorCategory;
use ego_service_sdk::error::{ServiceError, ServiceErrorTrait};
use ego_service_sdk::runtime::RuntimeError;
#[allow(unused_imports)]
use ego_service_sdk_macros::operation;
use ego_service_sdk_macros::service;

// ---------------------------------------------------------------------------
// Shared types
// ---------------------------------------------------------------------------

#[derive(Debug)]
pub struct GoldenOrderError(pub String);

impl ServiceErrorTrait for GoldenOrderError {
    fn code(&self) -> &str {
        "GOLDEN_ORDER_ERROR"
    }
    fn category(&self) -> ErrorCategory {
        ErrorCategory::Business
    }
    fn message(&self) -> String {
        self.0.clone()
    }
}

impl From<RuntimeError> for GoldenOrderError {
    fn from(e: RuntimeError) -> Self {
        GoldenOrderError(e.to_string())
    }
}

#[derive(Debug)]
pub struct MyProjection;

#[derive(Debug)]
pub struct MyAdapter;

// ---------------------------------------------------------------------------
// Trait expansion — ServiceDescriptor snapshots
// ---------------------------------------------------------------------------

#[service(version = "1.0.0")]
pub trait GoldenOrderService {
    #[operation]
    async fn place_order(&self, product_id: String) -> Result<String, GoldenOrderError>;
}

#[test]
fn golden_trait_descriptor_order_service() {
    // This snapshot captures the full ServiceDescriptor generated by #[service]
    // for a single-operation trait with a domain error type.
    // All fields (name, version, operations, input/output types, error types)
    // are deterministic strings — no TypeIds involved.
    insta::assert_debug_snapshot!(
        "trait_descriptor_order_service",
        <GoldenOrderServiceTag as ServiceContract>::descriptor()
    );
}

// ---------------------------------------------------------------------------
// Multi-op trait
// ---------------------------------------------------------------------------

#[service(version = "1.0.0")]
pub trait GoldenPaymentService {
    #[operation]
    async fn charge(&self, amount: u64) -> Result<String, ServiceError>;

    #[operation]
    async fn refund(&self, amount: u64) -> Result<String, ServiceError>;
}

#[test]
fn golden_trait_descriptor_payment_service() {
    // Multi-operation trait with ServiceError (standard error type).
    insta::assert_debug_snapshot!(
        "trait_descriptor_payment_service",
        <GoldenPaymentServiceTag as ServiceContract>::descriptor()
    );
}

// ---------------------------------------------------------------------------
// Struct expansion — Injectable::dependencies() snapshots
// ---------------------------------------------------------------------------

/// Struct with mixed DI fields.
#[allow(dead_code)]
#[service]
struct GoldenInjectableService {
    projection: ProjectionRef<MyProjection>,
    adapter: AdapterRef<MyAdapter>,
    name: String,
}

#[test]
fn golden_struct_dependencies_mixed() {
    // dependencies() returns DepKey values with TypeId. TypeId is non-deterministic
    // across compilations, so we normalise it with a filter.
    let deps = <GoldenInjectableService as Injectable>::dependencies();

    // Order is determined by field declaration order.
    // We snapshot the Debug output with TypeId values replaced by a placeholder.
    insta::with_settings!({
        filters => vec![
            (r"TypeId\(\{[^}]*\}\)", "TypeId(<opaque>)"),
            (r"TypeId\([^)]*\)", "TypeId(<opaque>)"),
        ],
    }, {
        insta::assert_debug_snapshot!("struct_dependencies_mixed", deps);
    });
}

/// Struct with only plain fields — dependencies() must be empty.
#[allow(dead_code)]
#[service]
struct GoldenPlainService {
    name: String,
    count: u32,
}

#[test]
fn golden_struct_dependencies_empty() {
    let deps = <GoldenPlainService as Injectable>::dependencies();
    insta::assert_debug_snapshot!("struct_dependencies_empty", deps);
}

/// Struct with a single projection dep.
#[allow(dead_code)]
#[service]
struct GoldenSingleProjectionService {
    projection: ProjectionRef<MyProjection>,
    name: String,
}

#[test]
fn golden_struct_dependencies_single_projection() {
    let deps = <GoldenSingleProjectionService as Injectable>::dependencies();
    insta::with_settings!({
        filters => vec![
            (r"TypeId\(\{[^}]*\}\)", "TypeId(<opaque>)"),
            (r"TypeId\([^)]*\)", "TypeId(<opaque>)"),
        ],
    }, {
        insta::assert_debug_snapshot!("struct_dependencies_single_projection", deps);
    });
}
