//! Order Service Example — full developer journey.
//!
//! This example demonstrates the intended developer experience for the Service SDK:
//!
//! ```ignore
//! // 1. Define a service contract with #[service] and #[operation] macros
//! // 2. Implement the contract with #[service] on the struct
//! // 3. Build the runtime with entities and services
//! // 4. Invoke the service via the generated proxy
//! ```
//!
//! ## Note
//!
//! This is an illustrative example. The `#[service]` and `#[operation]` proc-macros
//! require the `ego-service-sdk-macros` crate. This example shows the manual equivalent
//! of what those macros generate.

use async_trait::async_trait;
use ego_service_sdk::context::ServiceContext;
use ego_service_sdk::contract::{ContractVersion, OperationDescriptor, ServiceDescriptor};

// ---------------------------------------------------------------------------
// Domain types
// ---------------------------------------------------------------------------

/// A command to create a new order.
#[derive(Debug, Clone)]
pub struct CreateOrder {
    pub product_id: String,
    pub quantity: u32,
}

/// The identifier for a created order.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct OrderId(pub String);

/// Errors that can occur in the order domain.
#[derive(Debug, thiserror::Error)]
pub enum OrderError {
    #[error("Product not found: {0}")]
    ProductNotFound(String),
    #[error("Insufficient inventory for product {0}")]
    InsufficientInventory(String),
    #[error("Order not found: {0}")]
    OrderNotFound(String),
}

// ---------------------------------------------------------------------------
// Service contract trait (what #[service] would generate)
// ---------------------------------------------------------------------------

/// The order service contract.
///
/// In production, this would be declared with:
/// ```ignore
/// #[service(version = "1.0.0")]
/// pub trait OrderService {
///     #[operation]
///     async fn create_order(&self, cmd: CreateOrder) -> Result<OrderId, OrderError>;
/// }
/// ```
#[async_trait]
pub trait OrderService: Send + Sync {
    /// Create a new order.
    async fn create_order(&self, cmd: CreateOrder) -> Result<OrderId, OrderError>;
}

// ---------------------------------------------------------------------------
// Service implementation (what #[service] on struct would generate)
// ---------------------------------------------------------------------------

/// Concrete implementation of `OrderService`.
///
/// In production, field dependencies like `EntityRef<Order>` would be
/// auto-resolved by the runtime:
/// ```ignore
/// #[service]
/// pub struct OrderServiceImpl {
///     orders: EntityRef<Order>,
/// }
/// ```
pub struct OrderServiceImpl;

#[async_trait]
impl OrderService for OrderServiceImpl {
    async fn create_order(&self, cmd: CreateOrder) -> Result<OrderId, OrderError> {
        // In a real implementation, this would persist via an EntityRef<Order>.
        // For this example, we return a mock order ID.
        let id = OrderId(format!("ord-{}", cmd.product_id));
        Ok(id)
    }
}

// ---------------------------------------------------------------------------
// Example usage
// ---------------------------------------------------------------------------

#[tokio::main]
async fn main() -> Result<(), Box<dyn std::error::Error>> {
    // 1. Create the service implementation
    let service = OrderServiceImpl;

    // 2. Build a service descriptor (normally generated by #[service])
    let descriptor = ServiceDescriptor {
        name: "OrderService".to_string(),
        version: ContractVersion::new(1, 0, 0),
        operations: vec![OperationDescriptor {
            name: "create_order".to_string(),
            input: vec!["CreateOrder".to_string()],
            output: "OrderId".to_string(),
            errors: vec!["OrderError".to_string()],
            description: None,
            metadata: std::collections::HashMap::new(),
        }],
        description: None,
        metadata: std::collections::HashMap::new(),
    };

    println!("Service: {}", descriptor.name);
    println!("Version: {}", descriptor.version);
    println!("Operations: {}", descriptor.operations.len());

    // 3. Create an invocation context
    let context = ServiceContext::new()
        .with_tenant_id("tenant-acme")
        .with_correlation_id("req-123")
        .with_trace_id("trace-456");

    // 4. Invoke within the context scope
    let result = context
        .scope(|| async {
            let current = ServiceContext::current();
            if let Some(ctx) = current {
                println!("Invoking within tenant: {:?}", ctx.tenant_id());
            }

            // Call the service
            let cmd = CreateOrder {
                product_id: "prod-42".to_string(),
                quantity: 10,
            };
            service.create_order(cmd).await
        })
        .await;

    // 5. Verify the result
    match result {
        Ok(order_id) => {
            println!("Order created: {:?}", order_id);
            assert_eq!(order_id, OrderId("prod-42".to_string()));
        }
        Err(e) => {
            eprintln!("Order creation failed: {}", e);
            return Err(e.into());
        }
    }

    // 6. Demonstrate ServiceContext::current() is None outside scope
    let outside_ctx = ServiceContext::current();
    assert!(outside_ctx.is_none());
    println!("Outside scope: context is {:?}", outside_ctx);

    println!("\n✓ Example completed successfully");
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;

    #[tokio::test]
    async fn test_create_order_success() {
        let service = OrderServiceImpl;
        let cmd = CreateOrder {
            product_id: "test-product".to_string(),
            quantity: 1,
        };
        let result = service.create_order(cmd).await;
        assert!(result.is_ok());
        assert_eq!(result.unwrap(), OrderId("test-product".to_string()));
    }

    #[tokio::test]
    async fn test_context_scoping() {
        let context = ServiceContext::new().with_tenant_id("test-tenant");

        let captured = context.scope(|| async { ServiceContext::current() }).await;
        assert!(captured.is_some());
        assert_eq!(captured.unwrap().tenant_id(), Some("test-tenant"));
    }
}
