[package]
name = "ego-service-sdk"
version = "0.1.0"
edition = "2021"

[dependencies]
async-trait = "0.1"
tokio = { version = "1.0", features = ["full"] }
tokio-util = { version = "0.7" }
semver = "1"
thiserror = "1.0"
kitlogger = { git = "https://github.com/pablogore/kitlogger.git", branch = "develop" }
ego-security-sdk = { path = "../security-sdk" }

[dev-dependencies]
ego-service-sdk-macros = { path = "../service-sdk-macros" }
serde = { version = "1.0", features = ["derive"] }
tracing = "0.1"
tracing-subscriber = "0.3"
mockall = "0.12"
insta = { version = "1", features = ["filters"] }