//! Resolvable trait and container for typed proxy resolution at runtime.
//!
//! The `#[service]` macro generates a `Resolvable` impl on every service tag,
//! enabling `Runtime::resolve<T: Resolvable>()` to produce typed proxies from
//! raw registry entries.

use std::any::Any;
use std::sync::{Arc, Weak};

use crate::contract::ServiceContract;
use crate::interceptor::InterceptorChain;

use super::{RuntimeError, RuntimeInner};

/// Concrete wrapper that enables storing `Arc<dyn Trait>` as `Arc<dyn Any>`.
///
/// # Why this exists
///
/// `Arc<dyn Any>` can be downcast to concrete types but NOT to `Arc<dyn Trait>`
/// because `dyn Trait` does not implement `Any`. This wrapper provides a concrete
/// `'static` type (`ResolvableContainer<T>`) that holds the `Arc<T>` and can be
/// stored in the registry as `Arc<dyn Any + Send + Sync>`.
///
/// At resolve time, the generated `Resolvable::create_proxy` impl downcasts back
/// to `Arc<ResolvableContainer<dyn Trait>>` and extracts the inner `Arc<dyn Trait>`.
#[repr(transparent)]
pub struct ResolvableContainer<T: ?Sized + Send + Sync + 'static>(pub Arc<T>);

// SAFETY: ResolvableContainer<T> is Send+Sync when T: Send+Sync because Arc<T> is Send+Sync.
unsafe impl<T: ?Sized + Send + Sync + 'static> Send for ResolvableContainer<T> {}
unsafe impl<T: ?Sized + Send + Sync + 'static> Sync for ResolvableContainer<T> {}

/// Trait generated on every service tag to enable typed proxy resolution.
///
/// Implemented by the `#[service]` macro for every annotated trait.
/// Connects a `Tag` type (registry key) to its corresponding `Proxy` type
/// and provides a factory method to create proxies from raw registry entries.
///
/// # Usage
///
/// ```
/// use std::sync::Arc;
///
/// use ego_service_sdk::async_trait::async_trait;
/// use ego_service_sdk::context::ServiceContext;
/// use ego_service_sdk::error::ServiceError;
/// use ego_service_sdk::runtime::RuntimeBuilder;
/// use ego_service_sdk_macros::{operation, service};
///
/// #[service(version = "1.0.0")]
/// pub trait GreeterService {
///     #[operation]
///     async fn greet(&self, ctx: ServiceContext, name: String) -> Result<String, ServiceError>;
/// }
///
/// struct GreeterServiceImpl;
///
/// #[async_trait]
/// impl GreeterService for GreeterServiceImpl {
///     async fn greet(&self, _ctx: ServiceContext, name: String) -> Result<String, ServiceError> {
///         Ok(format!("hello, {name}"))
///     }
/// }
///
/// #[tokio::main]
/// async fn main() {
///     let inner: Arc<dyn GreeterService> = Arc::new(GreeterServiceImpl);
///     let runtime = RuntimeBuilder::new()
///         .with_service::<GreeterServiceTag>(inner)
///         .unwrap()
///         .build();
///
///     // `GreeterServiceTag: Resolvable` is generated by `#[service]` — it's
///     // what makes this typed proxy resolution possible.
///     let proxy = runtime.resolve::<GreeterServiceTag>().unwrap();
///     let out = proxy.greet(ServiceContext::new(), "world".to_string()).await.unwrap();
///     assert_eq!(out, "hello, world");
/// }
/// ```
pub trait Resolvable: ServiceContract {
    /// The proxy type returned by `Runtime::resolve`.
    type Proxy: Send + Sync;

    /// The trait object this tag fronts — the type link `with_service::<Tag>`
    /// needs to name the `Arc<Tag::Service>` it accepts. This is the only
    /// job of this associated type; it is not a general service descriptor
    /// (see design.md's scope note — further metadata belongs on
    /// `ServiceContract`, not here).
    type Service: ?Sized + Send + Sync + 'static;

    /// Creates a typed proxy from a raw registry entry.
    ///
    /// The `inner` must have been stored as `Arc<ResolvableContainer<dyn Trait>>`
    /// where `Trait` is the service trait associated with this tag.
    fn create_proxy(
        inner: Arc<dyn Any + Send + Sync>,
        chain: Arc<InterceptorChain>,
        runtime: Weak<RuntimeInner>,
    ) -> Result<Self::Proxy, RuntimeError>;
}

/// Links a macro-annotated service struct to the resolution `Tag` of the
/// trait it implements (CORE-028 Stage 2B).
///
/// Generated by `#[service(impl_of = Trait)]` on a struct — never
/// hand-implemented. `into_service` is a concrete `Arc<Self> -> Arc<dyn
/// Trait>` unsize coercion written literally by the macro at expansion time
/// (`self`); this is what makes the coercion valid Rust, since a generic
/// bound naming "whichever trait `Tag::Service` projects to" is not
/// expressible (see `AppBuilder::service`'s design-deviation note in
/// `crate::app`, which this trait resolves).
///
/// A hand-rolled `Injectable` struct the macro never touched has no
/// `HasServiceTag` impl and registers permanently via
/// `AppBuilder::service_with_tag` instead.
pub trait HasServiceTag: 'static {
    /// The resolution `Tag` for the trait this struct implements.
    type Tag: Resolvable + 'static;

    /// Concrete coercion from `Arc<Self>` to the trait object `Tag::Service`
    /// projects to. The macro-generated body is always `self` — an ordinary
    /// unsize coercion, valid because the macro writes `dyn Trait` literally.
    fn into_service(self: Arc<Self>) -> Arc<<Self::Tag as Resolvable>::Service>;
}
