[package]
name = "ego-transport"
version = "0.1.0"
edition = "2021"

[dependencies]
ego-domain = { path = "../domain" }
ego-application = { path = "../application" }
ego-service-sdk = { path = "../service-sdk" }
ego-security-sdk = { path = "../security-sdk" }
axum = "0.7"
tokio = { version = "1", features = ["full"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
async-trait = { workspace = true }

[dev-dependencies]
mockall = { workspace = true }
tokio-test = "0.4"
ego-service-sdk-macros = { path = "../service-sdk-macros" }
security-jwt = { path = "../security-jwt" }
jsonwebtoken = "9"
