[package]
name = "ego-config-sdk"
version = "0.1.0"
edition = "2021"

[features]
test-helpers = []

[dependencies]
thiserror = "1.0"
serde_json = "1.0"
serde = { version = "1.0", features = ["derive"] }
kit-config = { git = "https://github.com/pablogore/kit-config.git", branch = "master", features = ["config-loaders"] }

[dev-dependencies]
tokio = { version = "1.0", features = ["macros", "rt-multi-thread"] }
tempfile = "3"
